apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
  namespace: exbanka-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: bank-service
          image: ghcr.io/raf-si-2025/exbanka-2-backend-bank-service:latest
          imagePullPolicy: Always
          ports:
            - { name: http, containerPort: 8080 }
            - { name: grpc, containerPort: 50051 }
          env:
            - { name: DB_SCHEMA, value: "core_banking" }
            - { name: HTTP_ADDR, value: "0.0.0.0:8080" }
            - { name: GRPC_ADDR, value: "0.0.0.0:50051" }
            - { name: DB_USER,     valueFrom: { secretKeyRef: { name: db-pguser-bankadmin, key: user } } }
            - { name: DB_PASSWORD, valueFrom: { secretKeyRef: { name: db-pguser-bankadmin, key: password } } }
          envFrom:
            - configMapRef: { name: exbanka-config }
            - secretRef:    { name: exbanka-secrets }
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
  namespace: exbanka-2
spec:
  selector:
    app: bank-service
  ports:
    - { name: http, port: 8080, targetPort: 8080 }
    - { name: grpc, port: 50051, targetPort: 50051 }
